-- MySQL Script generated by MySQL Workbench
-- Mon Aug 16 18:06:23 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`SHOP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SHOP` (
  `shop_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  `address` VARCHAR(65) NOT NULL,
  `area` VARCHAR(15) NULL,
  PRIMARY KEY (`shop_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CATEGORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CATEGORY` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `Category` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `Category_UNIQUE` (`Category` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCTS` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `Product` VARCHAR(20) NOT NULL,
  `Price` DECIMAL(2) NOT NULL,
  `CATEGORY_category_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `CATEGORY_category_id`),
  UNIQUE INDEX `Product_UNIQUE` (`Product` ASC) VISIBLE,
  INDEX `fk_PRODUCTS_CATEGORY1_idx` (`CATEGORY_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTS_CATEGORY1`
    FOREIGN KEY (`CATEGORY_category_id`)
    REFERENCES `mydb`.`CATEGORY` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENT` (
  `client_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(15) NOT NULL,
  `surname` VARCHAR(20) NOT NULL,
  `age` INT NULL,
  PRIMARY KEY (`client_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BILL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BILL` (
  `idBILL` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `SHOP_shop_id` INT NOT NULL,
  `PRODUCTS_product_id` INT NOT NULL,
  `Quantity` INT NULL,
  `Sub-total` DECIMAL(2) GENERATED ALWAYS AS (Price FROM PRODUCTS * Quantity),
  `CLIENT_client_id` INT NOT NULL,
  PRIMARY KEY (`idBILL`, `SHOP_shop_id`, `PRODUCTS_product_id`, `CLIENT_client_id`),
  UNIQUE INDEX `ID_UNIQUE` (`idBILL` ASC) VISIBLE,
  INDEX `fk_BILL_SHOP_idx` (`SHOP_shop_id` ASC) VISIBLE,
  INDEX `fk_BILL_PRODUCTS1_idx` (`PRODUCTS_product_id` ASC) VISIBLE,
  INDEX `fk_BILL_CLIENT1_idx` (`CLIENT_client_id` ASC) VISIBLE,
  CONSTRAINT `fk_BILL_SHOP`
    FOREIGN KEY (`SHOP_shop_id`)
    REFERENCES `mydb`.`SHOP` (`shop_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BILL_PRODUCTS1`
    FOREIGN KEY (`PRODUCTS_product_id`)
    REFERENCES `mydb`.`PRODUCTS` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BILL_CLIENT1`
    FOREIGN KEY (`CLIENT_client_id`)
    REFERENCES `mydb`.`CLIENT` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLOYEE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLOYEE` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(15) NOT NULL,
  `surname` VARCHAR(20) NOT NULL,
  `SHOP_shop_id` INT NOT NULL,
  PRIMARY KEY (`employee_id`, `SHOP_shop_id`),
  INDEX `fk_EMPLOYEE_SHOP1_idx` (`SHOP_shop_id` ASC) VISIBLE,
  CONSTRAINT `fk_EMPLOYEE_SHOP1`
    FOREIGN KEY (`SHOP_shop_id`)
    REFERENCES `mydb`.`SHOP` (`shop_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
